session:
  targets:
    - lib:tricorder
    - exe:tricorder-exe
    - lib:atelier
    - lib:atelier-testing
    - test:atelier-test
    - test:tricorder-test

observability:
  log_file: /tmp/tricorder.log
  metrics_port: 9091
