name:                tricorder
version:             0.1.0.0
synopsis:            TODO write a short description
description:         TODO write a long description
author:              Christian Georgii
maintainer:          cgeorgii@gmail.com
license:             MIT

language: GHC2021

ghc-options:
- -Weverything
# SafeHaskell is a myth
- -Wno-unsafe
- -Wno-missing-safe-haskell-mode
# Removes all the pros of type inference
- -Wno-monomorphism-restriction
# Most of the time completely unnecessary
- -Wno-missing-kind-signatures
- -Wno-missing-poly-kind-signatures
# Mechanical noise — roles on simple newtypes are obvious
- -Wno-missing-role-annotations
# Very tedious to enforce for _all_ local bindings
- -Wno-missing-local-signatures
# Tedious because it also enforces an explicit import list on records
- -Wno-missing-import-lists
# Noise
- -Wno-implicit-prelude
# Forces us to write ': instead of : for Effectful's (:) operator, and many
# other tedious things.
- -Wno-unticked-promoted-constructors
# False positive flags `base` and `tasty-discover`, unfortunately.
#
# `base` is used directly by the `Paths_*.hs` module generated by cabal, so
# we need to keep it as a dependency.
#
# `tasty-discover` is used in our testing harness to ease running test files
# through its compiler plugin. We don't use `tasty-discover` directly in our
# code though, so it is falsely flagged as unused.
- -Wno-unused-packages
- -O0
- -fplugin=Effectful.Plugin
- -threaded

dependencies:
- effectful-core
- effectful-plugin

default-extensions:
- BlockArguments
- DataKinds
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FlexibleContexts
- GADTs
- LambdaCase
- MultiWayIf
- OverloadedLabels
- OverloadedRecordDot
- OverloadedStrings
- StrictData
- TemplateHaskell
- TypeFamilies

library:
  source-dirs: tricorder/src
  dependencies:
  - name: base
    mixin:
      - hiding (Prelude)
  - atelier-prelude
  - atelier
  - aeson
  - ansi-terminal
  - brick
  - bytestring
  - containers
  - data-default
  - directory
  - effectful
  - effectful-th
  - filepath
  - ghcid
  - mtl
  - network
  - hashable
  - optparse-applicative
  - typed-process
  - stm
  - text
  - time
  - time-units
  - vty
  - vty-crossplatform
  - Cabal-syntax
  - yaml

internal-libraries:
  atelier:
    source-dirs: atelier/src
    dependencies:
    - name: base
      mixin:
        - hiding (Prelude)
    - atelier-prelude
    - aeson
    - base64-bytestring
    - bytestring
    - casing
    - containers
    - contra-tracer
    - daemons
    - data-default
    - directory
    - effectful
    - effectful-th
    - filepath
    - fsnotify
    - ki
    - stm
    - hasql
    - hasql-pool
    - hasql-transaction
    - hs-opentelemetry-api
    - hs-opentelemetry-exporter-otlp
    - hs-opentelemetry-sdk
    - http-api-data
    - ki
    - list-t
    - http-types
    - prometheus-client
    - prometheus-metrics-ghc
    - wai
    - warp
    - rel8
    - stm-containers
    - text
    - time
    - time-units
    - unagi-chan
    - unix
    - unordered-containers
    - uuid

  atelier-prelude:
    source-dirs: atelier/prelude
    dependencies:
    - base
    - relude


  atelier-testing:
    source-dirs: atelier/testing
    dependencies:
    - name: base
      mixin:
        - hiding (Prelude)
    - atelier-prelude
    - atelier
    - hasql
    - hasql-pool
    - hspec
    - postgres-options
    - string-conversions
    - text
    - tmp-postgres
    - unix
    - uuid

executables:
  tricorder-exe:
    main:                Main.hs
    source-dirs:         tricorder/app
    ghc-options:
    - '"-with-rtsopts=-N -T"'
    dependencies:
    - name: base
      mixin:
        - hiding (Prelude)
    - atelier-prelude
    - tricorder
    - atelier
    - effectful
    - data-default

tests:
  atelier-test:
    main:                Driver.hs
    source-dirs:         atelier/test
    ghc-options:
    # Complains about `test/Driver.hs` emitted by tasty-discover, and is handled by
    # our fourmolu config.
    - -Wno-prepositive-qualified-module
    - -threaded
    build-tools:
    - tasty-discover:tasty-discover
    dependencies:
    - name: base
      mixin:
        - hiding (Prelude)
    - atelier-prelude
    - atelier
    - async
    - containers
    - effectful
    - hs-opentelemetry-api
    - hedgehog
    - hspec
    - hspec-hedgehog
    - stm
    - tasty
    - tasty-hspec
    - time

  tricorder-test:
    main:                Driver.hs
    source-dirs:         tricorder/test
    ghc-options:
    - -Wno-prepositive-qualified-module
    - -threaded
    build-tools:
    - tasty-discover:tasty-discover
    dependencies:
    - name: base
      mixin:
        - hiding (Prelude)
    - atelier-prelude
    - tricorder
    - Cabal-syntax
    - aeson
    - atelier
    - containers
    - data-default
    - effectful
    - hspec
    - stm
    - tasty
    - tasty-discover
    - tasty-hspec
    - text
    - time
    - time-units
