name:                atelier-prelude
version:             0.1.0.0
synopsis:            Custom relude-based prelude with Effectful conventions
description:         A custom prelude based on relude, adapted for Effectful — part of the atelier toolkit.
author:              Christian Georgii
maintainer:          cgeorgii@gmail.com
license:             MIT
license-file:        LICENSE
github:              atelier-hub/tricorder
category:            Prelude

extra-doc-files:
- CHANGELOG.md

language: GHC2021

ghc-options:
- -Weverything
- -Wno-unsafe
- -Wno-missing-safe-haskell-mode
- -Wno-monomorphism-restriction
- -Wno-missing-kind-signatures
- -Wno-missing-poly-kind-signatures
- -Wno-missing-role-annotations
- -Wno-missing-local-signatures
- -Wno-missing-import-lists
- -Wno-implicit-prelude
- -Wno-unticked-promoted-constructors
- -Wno-unused-packages

default-extensions:
- BlockArguments
- DataKinds
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FlexibleContexts
- GADTs
- LambdaCase
- MultiWayIf
- OverloadedLabels
- OverloadedRecordDot
- OverloadedStrings
- StrictData
- TemplateHaskell
- TypeFamilies

library:
  source-dirs: src
  dependencies:
  - base
  - effectful-core
  - relude
