- &version-base ">=4.20 && < 4.21"

- &dep-Cabal-syntax "Cabal-syntax >=3.12 && <3.13"
- &dep-aeson "aeson >=2.2 && <2.3"
- &dep-ansi-terminal "ansi-terminal >=1.1 && <1.2"
- &dep-async "async >=2.2 && <2.3"
- &dep-atelier-core "atelier-core >=0.1 && <0.2"
- &dep-atelier-db "atelier-db >=0.1 && <0.2"
- &dep-atelier-prelude "atelier-prelude >=0.1 && <0.2"
- &dep-base64-bytestring "base64-bytestring >=1.2 && <1.3"
- &dep-brick "brick >=2.10 && <2.11"
- &dep-bytestring "bytestring >=0.12 && <0.13"
- &dep-casing "casing >=0.1 && <0.2"
- &dep-containers "containers >=0.7 && <0.8"
- &dep-contra-tracer "contra-tracer >=0.2 && <0.3"
- &dep-daemons "daemons >=0.4 && <0.5"
- &dep-data-default "data-default >=0.8 && <0.9"
- &dep-directory "directory >=1.3 && <1.4"
- &dep-effectful "effectful >=2.6 && <2.7"
- &dep-effectful-core "effectful-core >=2.6 && <2.7"
- &dep-effectful-plugin "effectful-plugin >=2.0 && <2.1"
- &dep-effectful-th "effectful-th >=1.0 && <1.1"
- &dep-filepath "filepath >=1.5 && <1.6"
- &dep-fsnotify "fsnotify >=0.4 && <0.5"
- &dep-hashable "hashable >=1.5 && <1.6"
- &dep-hasql "hasql >=1.9 && <1.10"
- &dep-hasql-pool "hasql-pool >=1.3 && <1.4"
- &dep-hasql-transaction "hasql-transaction >=1.2 && <1.3"
- &dep-hedgehog "hedgehog >=1.7 && <1.8"
- &dep-hs-opentelemetry-api "hs-opentelemetry-api >=0.3 && <0.4"
- &dep-hs-opentelemetry-exporter-otlp "hs-opentelemetry-exporter-otlp >=0.1 && <0.2"
- &dep-hs-opentelemetry-sdk "hs-opentelemetry-sdk >=0.1 && <0.2"
- &dep-hspec "hspec >=2.11 && <2.12"
- &dep-hspec-hedgehog "hspec-hedgehog >=0.3 && <0.4"
- &dep-http-api-data "http-api-data >=0.7 && <0.8"
- &dep-http-types "http-types >=0.12 && <0.13"
- &dep-ki "ki >=1.0 && <1.1"
- &dep-list-t "list-t >=1.0 && <1.1"
- &dep-megaparsec "megaparsec >=9.7 && <9.8"
- &dep-mtl "mtl >=2.3 && <2.4"
- &dep-network "network >=3.2 && <3.3"
- &dep-optparse-applicative "optparse-applicative >=0.19 && <0.20"
- &dep-postgres-options "postgres-options >=0.2 && <0.3"
- &dep-process "process >=1.6 && <1.7"
- &dep-prometheus-client "prometheus-client >=1.1 && <1.2"
- &dep-prometheus-metrics-ghc "prometheus-metrics-ghc >=1.0 && <1.1"
- &dep-rel8 "rel8 >=1.7 && <1.8"
- &dep-relude "relude >=1.2 && <1.3"
- &dep-stm "stm >=2.5 && <2.6"
- &dep-stm-containers "stm-containers >=1.2 && <1.3"
- &dep-string-conversions "string-conversions >=0.4 && <0.5"
- &dep-tasty "tasty >=1.5 && <1.6"
- &dep-tasty-discover "tasty-discover >=5.2 && <5.3"
- &dep-tasty-hspec "tasty-hspec >=1.2 && <1.3"
- &dep-template-haskell "template-haskell >=2.22 && <2.23"
- &dep-text "text >=2.1 && <2.2"
- &dep-time "time >=1.12 && <1.13"
- &dep-time-units "time-units >=1.0 && <1.1"
- &dep-tmp-postgres "tmp-postgres >=1.35 && <1.36"
- &dep-typed-process "typed-process >=0.2 && <0.3"
- &dep-unagi-chan "unagi-chan >=0.4 && <0.5"
- &dep-unix "unix >=2.8 && <2.9"
- &dep-unordered-containers "unordered-containers >=0.2 && <0.3"
- &dep-uuid "uuid >=1.3 && <1.4"
- &dep-vty "vty >=6.5 && <6.6"
- &dep-vty-crossplatform "vty-crossplatform >=0.5 && <0.6"
- &dep-wai "wai >=3.2 && <3.3"
- &dep-warp "warp >=3.4 && <3.5"
- &dep-yaml "yaml >=0.11 && <0.12"
