observability:
  environment: "dev"
  prometheus:
    port: 9090
    scrape_interval: "5s"
    evaluation_interval: "5s"
    targets:
      app: "localhost:9091"
      node_exporter: "localhost:9100"
  grafana:
    port: 3001
    host: "0.0.0.0"
    admin_user: "admin"
    admin_password: "admin"
  tempo:
    http_port: 3200
    otlp_http_port: 4318
    block_retention: "24h"
    max_block_duration: "5m"
  loki:
    http_port: 3100
    retention_period: "24h"
  node_exporter:
    port: 9100
