name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  check:
    name: Check ${{ matrix.system }}/${{ matrix.ghc-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-14
          - ubuntu-latest
        ghc-version:
          - ghc9102
          - ghc912
          - ghc914
          - ghc98
        include:
          - os: macos-14
            system: aarch64-darwin
          - os: ubuntu-latest
            system: x86_64-linux
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            extra-substituters = https://cache.iog.io
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
      - uses: cachix/cachix-action@v17
        with:
          name: atelier
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build '.#legacyChecks.${{ matrix.system }}.${{ matrix.ghc-version }}.all' -L
